# Generated by Django 3.1.7 on 2021-02-23 14:47

import AdminApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR_SECTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Waiting for Witness', 'Waiting for Witness'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('DOB', models.DateField()),
                ('contact_No', models.PositiveIntegerField()),
                ('userType', models.CharField(choices=[('Victim', 'Victim'), ('Police Staff', 'Police Staff'), ('SP', 'SP')], default='Victim', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('adhaar_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track_FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('InProgress', 'InProgress'), ('Waiting for Witness', 'Waiting for Witness'), ('Cancelled', 'Cancelled'), ('Resolved', 'Resolved'), ('Forwared to Court', 'Forwared to Court')], default='InProgress', max_length=50)),
                ('police_station', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_fir', to='AdminApp.fir_section')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField(default=AdminApp.models.OTP.Otp_generator)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fir_section',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userprofile'),
        ),
    ]
