# Generated by Django 3.1.7 on 2021-02-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir_section',
            old_name='name',
            new_name='place_of_incident',
        ),
        migrations.AddField(
            model_name='fir_section',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track_fir',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fir_section',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting for Witness', 'Waiting for Witness'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
